openapi: 3.0.0
info:
  title: Integram
  version: 1.0.0
  description: Integram APIs with Swagger
  contact: {
    email: talaviyasanket01@gmail.com
  }
servers:
  - url: https://integram-puez.onrender.com/api/v1
  - url: http://localhost:9000/api/v1
components:
  securitySchemes:
    userAuth:
      type: http
      scheme: bearer
    adminAuth:
      type: http
      scheme: bearer
tags:
  - name: Auth
  - name: Users
  - name: Posts
paths:
  /auth/register:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
              example:
                email: example_user@gmail.com
                password: user1234
      responses:
        '200':
          description: Token Object
          content:
            application/json: {}
  /auth/login:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string,
                  format: email
                password:
                  type: string
              required:
                - email
                - password
              example:
                email: user1@gmail.com
                password: user1234
      responses:
        '200':
          description: Object with Token & isProfileCompleted property
          content:
            application/json: {}
  /auth/forgot-password/email:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
              required:
                - email
              example:
                email: user1@gmail.com
      responses:
        '200':
          description: Success response with reset Token
          content:
            application/json: {}
  /auth/verify-reset-otp:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  format: token
                otp:
                  type: integer
                  format: otp
              required:
                - token
                - otp
              example:
                otp: 1234
      responses:
        '200':
          description: Success response
          content:
            application/json: {}
  /auth/reset-password:
    put:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  format: token
                password:
                  type: string
              required:
                - token
                - password
              example:
                password: user5678
      responses:
        '200':
          description: Success response
          content:
            application/json: {}
  /users/profile:
    post:
      tags:
        - Users
      security:
        - userAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  type: string
                nickName:
                  type: string
                profileImage:
                  type: string
                mobile:
                  type: number
                country:
                  type: string
                occupation:
                  type: string 
                required:
                  - fullName
                  - nickName
                  - profileImage
                  - mobile
                  - gender
                  - country
                  - occupation
              example:
                fullName: Steve Rogers
                nickName: Steve
                profileImage: https://picsum.photos/200
                mobile: 9876543210
                country: India
                occupation: UI/UX Designer
      responses:
        '200':
          description: user object
          content:
            application/json: {}
    get:
      tags:
        - Users
      security:
        - userAuth: []
      responses:
        '200':
          description: User profile object
          content:
            application/json: {}
    put:
      tags:
        - Users
      security:
        - userAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                fullName:
                  type: string
                nickName:
                  type: string
                profileImage:
                  type: string
                mobile:
                  type: number
                gender:
                  type: string
                  enum: [male, female, other]
                country:
                  type: string
                occupation:
                  type: string
              example:
                fullName: Steve Rogers
                nickName: Steve
                profileImage: https://picsum.photos/200
                mobile: 9876543210
                country: United States
                occupation: Backend Developer
      responses:
        '200':
          description: updated User profile object
          content:
            application/json: {}
    delete:
      tags:
        - Users
      security:
        - userAuth: []
      responses:
        '200':
          description: empty object
          content:
            application/json: {}
  /posts:
    get:
      tags:
        - Posts
      security:
        - userAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
          description: page number for posts
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            default: 10
          description: number of posts per page
      responses:
        '200':
          description: posts array
          content:
            application/json: {}
    post:
      tags:
        - Posts
      security:
        - userAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                caption:
                  type: string
                imgURL:
                  type: string
              required:
                - imgURL
              example:
                caption: Visited New Mexico last week
                imgURL: https://picsum.photos/300
      responses:
        '200':
          description: post object
          content:
            application/json: {}
  /posts/toggle-like:
    post:
      tags:
        - Posts
      security:
        - userAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                postId:
                  type: string
                  format: objectId
                isLiked:
                  type: boolean
              required:
                - postId
                - isLiked
              example:
                postId: post-object-id
                isLiked: true
      responses:
        '200':
          description: isLiked field
          content:
            application/json: {}
  /posts/comments/{postId}:
    get:
      tags:
        - Posts
      security:
        - userAuth: []
      parameters:
        - name: postId
          in: path
          schema:
            type: string
            format: objectId
          required: true
          description: postId for comments
      responses:
        '200':
          description: comments array
          content:
            application/json: {}
  /posts/comment:
    post:
      tags:
        - Posts
      security:
        - userAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                postId:
                  type: string
                  format: objectId
                text:
                  type: string
              required:
                - postId
                - text
              example:
                postId: post-object-id
                text: Great! Keep it up
      responses:
        '200':
          description: comment object
          content:
            application/json: {}
    delete:
      tags:
        - Posts
      security:
        - userAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                commentId:
                  type: string
                  format: objectId
              required:
                - commentId
              example:
                commentId: comment-object-id
      responses:
        '200':
          description: empty object
          content:
            application/json: {}
  /posts/comment/reply:
    post:
      tags:
        - Posts
      security:
        - userAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                commentId:
                  type: string
                  format: objectId
                text:
                  type: string
              required:
                - commentId
                - text
              example:
                commentId: comment-object-id
                text: Yeah! Really nice
      responses:
        '200':
          description: comment object
          content:
            application/json: {}